apiVersion: apps/v1
kind: Deployment
metadata:
  name: simulation-generator
  labels:
    app: simulation-generator
spec:
  selector:
    matchLabels:
      app: simulation-generator
  template:
    metadata:
      labels:
        app: simulation-generator
    spec:
      containers:
      - name: simulation-generator
        image: eventerimacr.azurecr.io/simulation-generator:latest
        env:
        - name: BLOB_UPLOAD_URI
          value: "3"
        - name: BLOB_UPLOAD_SAS
          value: "2"
        - name: CONTAINER_NAME
          value: step1
        - name: REQUESTED_REQ_PER_SEC
          value: "1"
        - name: REQUESTED_SIMULATOR_TIME_IN_SEC
          value: "1"
        - name: APPLICATIONINSIGHTS_CONNECTION_STRING
          value: "ec931919-5abd-4202-a58e-7367823d824c"
      nodeSelector:
        "type": "simulator"
