name: Simulation - CI process

on:
  push:
    branches: 
      - main
    paths: 
      - 'code/Samples.Azure.Eventer.ServiceGenerator/**' 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Login to ACR'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}   
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./code/Samples.Azure.Eventer.ServiceGenerator/ --file code/Samples.Azure.Eventer.ServiceGenerator/Dockerfile --tag ${{ secrets.REGISTRY_LOGIN_SERVER }}/service-generator:${{ github.sha }}
    - name: Push the Docker image
      run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/service-generator:${{ github.sha }}