name: Simulation - CI process

env:
  PROJECT_NAME: 'simulation-generator'
  RESOURCE_GROUP: 'eventerim-rg'
  CLUSTER_NAME: 'eventerimaks'
  CONTAINER_REGISTRY: 'eventerimacr.azurecr.io'

on:
  workflow_dispatch:
    inputs:
      tags:
        required: false
        description: 'Test Manual'
  push:
    branches: 
      - main
    paths: 
      - 'code/Samples.Azure.Eventer.ServiceGenerator/**' 

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code 
        uses: actions/checkout@v3
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.AZURE_CREDENTIALS.clientId }}
          password: ${{ secrets.AZURE_CREDENTIALS.clientSecret }} 
      - name: Azure login
        id: login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Build the Docker image
        run: |
          docker build ./code/Samples.Azure.Eventer.ServiceGenerator/ --file code/Samples.Azure.Eventer.ServiceGenerator/Dockerfile --tag ${{ env.CONTAINER_REGISTRY }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
          docker build ./code/Samples.Azure.Eventer.ServiceGenerator/ --file code/Samples.Azure.Eventer.ServiceGenerator/Dockerfile --tag ${{ env.CONTAINER_REGISTRY }}/${{ env.PROJECT_NAME }}:latest
      - name: Push the Docker image
        run: |
          docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.PROJECT_NAME }}:${{ github.sha }}
          docker push ${{ env.CONTAINER_REGISTRY }}/${{ env.PROJECT_NAME }}:latest
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: '${{ env.RESOURCE_GROUP }}' 
          cluster-name: '${{ env.CLUSTER_NAME }}'